package pl.padport.app;

import static org.junit.Assert.*;
import static org.junit.Assume.assumeTrue;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import org.junit.Test;

public class GameCompatTest {
    private static final String INDEX="<html><body><script type=\"text/javascript\" src=\"js/main.js\"></script></body></html>";
    private static final String FOSSIL_FIRST="// Generated by RPG Maker.\r\nvar $plugins =\r\n[\r\n{\"name\":\"FOSSIL\",\"status\":true,\"description\":\"x\",\"parameters\":{}},";

    @Test public void elderfieldProfileIsMzOnly(){
        assertEquals(GameCompat.ELDERFIELD,GameCompat.profile(" Welcome to Elderfield ","MZ"));
        assertEquals("",GameCompat.profile("Welcome to Elderfield","MV"));
        assertEquals("",GameCompat.profile("Look Outside","MZ"));
        assertEquals("",GameCompat.profile(null,"MZ"));
    }
    @Test public void fossilFirstAndEnabledServesTheFossilEntryPage(){
        assertEquals(INDEX.replace("js/main.js","js/plugins/FOSSIL.js"),GameCompat.fossilEntry(INDEX,FOSSIL_FIRST));
    }
    @Test public void otherPluginListsKeepIndexHtml(){
        assertEquals(INDEX,GameCompat.fossilEntry(INDEX,FOSSIL_FIRST.replace("\"status\":true","\"status\":false")));
        assertEquals(INDEX,GameCompat.fossilEntry(INDEX,"var $plugins =\n[\n{\"name\":\"VisuMZ_0_CoreEngine\",\"status\":true},\n{\"name\":\"FOSSIL\",\"status\":true}"));
        assertEquals(INDEX,GameCompat.fossilEntry(INDEX,null));
        String custom="<script src=\"js/boot.js\"></script>";
        assertEquals(custom,GameCompat.fossilEntry(custom,FOSSIL_FIRST));
    }
    /** ELDERFIELD_GAME=<folder>: PadPort's page must equal the FOSSILindex.html that FOSSIL writes under NW.js. */
    @Test public void realGameMatchesFossilGeneratedPage() throws Exception {
        String game=System.getenv("ELDERFIELD_GAME");
        assumeTrue(game!=null&&!game.isEmpty());
        Path root=Path.of(game);
        String plugins=read(root.resolve("js/plugins.js")).substring(0,64*1024);
        assertEquals(read(root.resolve("FOSSILindex.html")),GameCompat.fossilEntry(read(root.resolve("index.html")),plugins));
    }
    private static String read(Path file) throws Exception {
        return new String(Files.readAllBytes(file),StandardCharsets.UTF_8);
    }
}
