"""Import a full-resolution launcher image and generate optional mask previews.

Usage: python tools/make_launcher_icon.py path/to/icon.png --preview-dir path/to/previews
Requires Pillow. Does not build an APK or change the source image.
The original pixel resolution is retained in drawable-nodpi, including for large
launcher tiles. Non-square sources are padded, not stretched. The adaptive icon
adds its 108-to-72 dp inset in XML, so the source image is not destructively resized.
"""
from __future__ import annotations

import argparse
from pathlib import Path

from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parents[1]
RES = ROOT / "app/src/main/res"
BACKGROUND = "#1a1819"
OLD_DENSITIES = ("mdpi", "hdpi", "xhdpi", "xxhdpi", "xxxhdpi")


def generate(source: Path, preview_dir: Path | None = None) -> None:
    with Image.open(source) as opened:
        image = opened.convert("RGBA")
    side = max(image.size)
    canvas = Image.new("RGBA", (side, side))
    canvas.alpha_composite(image, ((side - image.width) // 2, (side - image.height) // 2))
    folder = RES / "drawable-nodpi"
    folder.mkdir(parents=True, exist_ok=True)
    target = folder / "ic_padport_artwork.png"
    canvas.save(target, optimize=True)
    print(f"Original resolution: {side}x{side} RGBA -> {target}")
    # Remove only the density exports generated by the earlier version of this tool.
    for density in OLD_DENSITIES:
        old = RES / f"drawable-{density}" / "ic_padport_foreground.png"
        old.unlink(missing_ok=True)
    if preview_dir is None:
        return
    preview_dir.mkdir(parents=True, exist_ok=True)
    # Adaptive layers are 108 dp; the launcher masks the central 72 dp.
    foreground = canvas.resize((288, 288), Image.Resampling.LANCZOS)
    composite = Image.new("RGBA", (432, 432), BACKGROUND)
    composite.alpha_composite(foreground, (72, 72))
    visible = composite.crop((72, 72, 360, 360))
    sheet = Image.new("RGB", (944, 336), "#e0e0e0")
    draw = ImageDraw.Draw(sheet)
    for index, shape in enumerate(("square", "rounded", "circle")):
        mask = Image.new("L", visible.size, 0)
        painter = ImageDraw.Draw(mask)
        if shape == "circle":
            painter.ellipse((0, 0, 287, 287), fill=255)
        elif shape == "rounded":
            painter.rounded_rectangle((0, 0, 287, 287), radius=64, fill=255)
        else:
            painter.rectangle((0, 0, 287, 287), fill=255)
        preview = visible.copy()
        preview.putalpha(mask)
        preview.save(preview_dir / f"launcher-{shape}.png")
        x = 16 + index * 312
        sheet.paste(preview, (x, 12), preview)
        draw.text((x + 110, 308), shape, fill="#222222")
    sheet.save(preview_dir / "launcher-preview.png")
    print(f"Mask previews (approximate): {preview_dir / 'launcher-preview.png'}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", type=Path)
    parser.add_argument("--preview-dir", type=Path)
    args = parser.parse_args()
    generate(args.source, args.preview_dir)
